config/routes.rb
Rails.application.routes.draw do

  namespace :admins_backoffice do
    get 'welcome/index' #dashboard
    resources :admins
    resources :subjects
    resources :questions
  end
  devise_for :users
  devise_for :admins

  namespace :site do
    get  'welcome/index'
    get  'search', to: 'search#questions'
    get  'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end

  get 'welcome/index'
  get 'inicio', to: 'site/welcome#index'
  
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #kaminari
  paginates_per 5
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, counter_cache: true, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  #kaminari
  paginates_per 5

  #usar full text search. 
  #like passa por cada registro da tabela, 
  #degradando a performance para tabelas onde existem muitos registros.
  #isso pode ser resolvido com um full text search.

  #scopes são pesquisas no banco de dados. Retorna sempre um ActiveRelation
  scope :_search_, ->(page, term){
    includes(:answers, :subject)
    .where("lower(description) LIKE ?", "%#{term.downcase}%")
    .page(page)
  }

  scope :_search_subject_, ->(page, subject_id){
    includes(:answers, :subject)
    .where(subject_id: subject_id)
    .page(page)
  }

  scope :last_questions, ->(page){
    includes(:answers, :subject)
    .order('created_at desc')
    .page(page)
  }


end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions

  #kaminari
  paginates_per 5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :set_admin, only: [:edit,:update, :destroy]
  # before_action :verify_password, only: [:update]

  def index
    #console (like a break point. enable web console do debug application)
    @admins = Admin.all.page(params[:page])
  end

  def new 
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Adm included sucessfuly"
    elsif
      #renderizar de novo
      render :new
    end
  end

  def edit
  end
  
  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Adm saved sucessfuly"
    elsif
      #renderizar de novo
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Adm deleted sucessfuly"
    elsif
      #renderizar de novo
      render :index
    end
  end

  private
  
  def set_admin
    @admin = Admin.find(params[:id])
  end

  def params_admin
    params_admin = params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def verify_password
    #não obrigar a informar senha e confirmação ao atualizar admin
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end

end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "admins_backoffice"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protected

  def layout_by_resource
    devise_controller? ? "#{resource_class.to_s.downcase}_devise" : "application"
  end

end

app/controllers/site/answer_controller.rb
class Site::AnswerController < SiteController
  def question
    @answer = Answer.find(params[:answer_id])
  end
end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
  def questions
    @questions = Question._search_(params[:page], params[:term])
  end

  def subject 
    @questions = Question._search_subject_(params[:page], params[:subject_id])
  end

end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
    @questions = Question.last_questions(params[:page])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site"
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  layout "users_backoffice"
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attributes(object = nil, method = nil)
        if object && method
            object.model.human_attribute_name(method) 
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper

  def msg_questions
    case params[:action]
    when 'index'
      "Last added questions..."
    when 'subject'
      "Questions of subject \"#{params[:subject]}\""
    when 'questions'
      "Results for \"#{params[:term]}\""
    end
  end

end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/site/search/questions.html.erb
<%= render partial: 'site/shared/questions' %>

app/views/site/search/subject.html.erb
<%= render partial: 'site/shared/questions' %>

app/views/site/shared/_questions.html.erb
<div class="jumbotron">
  <h4><%= msg_questions%></h4>
  <%# <p>Find me in app/views/site/welcome/index.html.erb</p> %>

  <!-- 
  <div>
    <% if user_signed_in? %>
      <p>Usuario logado / <%= current_user.email %></p>
    <% else %>
      <p>Usuario deslogado</p>
    <% end %>
  </div>
  <div>
    <% if admin_signed_in? %>
      <p>Admin logado / <%= current_admin.email %></p>
    <% else %>
      <p>Admin deslogado</p>
    <% end %>
  </div>
  -->
</div>

<% @questions.each do |q| %>
  <%= form_with url: site_answer_path do |form| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <span class="label label-info" style="margin-right: 5px">
            <%= link_to "#{q.subject.description} (#{q.subject.questions_count})", site_search_subject_path(q.subject_id, q.subject.description), style:"color: white;" %>
          </span>
          <%= "#{q.id} - #{q.description}"%>
        </h3>
      </div>
      <div class="panel-body">
        <ul>
          <% i = 0%>
          <% q.answers.each do |a| %>
            <li style="list-style:none;">
              <div class="radio">
                <label>
                  <%= radio_button_tag 'answer_id', a.id %>
                  <% i += 1 %>
                  <%= "#{i} - #{a.description}" %>
                </label>
              </div>
            </li>
          <% end %>
          <li style="list-style:none;">
            <%= form.submit "Check", class:"btn btn-default", id: "submit_#{q.id}" %>
          </li>
        <ul>
      </div>
    </div>
  <% end %>
<% end %>
<div class="text-center">
  <%= paginate @questions%>
</div>