config/routes.rb
Rails.application.routes.draw do

  namespace :admins_backoffice do
    get 'welcome/index' #dashboard
    resources :admins
    resources :subjects
    resources :questions
  end
  devise_for :users
  devise_for :admins

  namespace :site do
    get  'welcome/index'
    get  'search', to: 'search#questions'
    get  'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end

  get 'welcome/index'
  get 'inicio', to: 'site/welcome#index'
  
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions

  #kaminari
  paginates_per 5
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :set_admin, only: [:edit,:update, :destroy]
  # before_action :verify_password, only: [:update]

  def index
    #console (like a break point. enable web console do debug application)
    @admins = Admin.all.page(params[:page])
  end

  def new 
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Adm included sucessfuly"
    elsif
      #renderizar de novo
      render :new
    end
  end

  def edit
  end
  
  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Adm saved sucessfuly"
    elsif
      #renderizar de novo
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Adm deleted sucessfuly"
    elsif
      #renderizar de novo
      render :index
    end
  end

  private
  
  def set_admin
    @admin = Admin.find(params[:id])
  end

  def params_admin
    params_admin = params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def verify_password
    #não obrigar a informar senha e confirmação ao atualizar admin
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end

end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
    before_action :set_question, only: [:edit,:update, :destroy]
    before_action :set_subject_options, only: [:create, :new, :edit, :update] 

    def index
      #includes evita fazer mais uma query pra buscar a descriçao dos subjects
      @questions = Question.includes(:subject).order(:id).page(params[:page])
    end
  
    def new 
      @question = Question.new
    end
  
    def create
      @question = Question.new(params_question)
      if @question.save
        redirect_to admins_backoffice_questions_path, notice: "Question included sucessfuly"
      elsif
        #renderizar de novo
        render :new
      end
    end
  
    def edit
    end
    
    def update
      if @question.update(params_question)
        redirect_to admins_backoffice_questions_path, notice: "Question saved sucessfuly"
      elsif
        #renderizar de novo
        render :edit
      end
    end
  
    def destroy
      if @question.destroy
        redirect_to admins_backoffice_questions_path, notice: "Question deleted sucessfuly"
      elsif
        #renderizar de novo
        render :index
      end
    end
  
    private

    def set_subject_options
        @subject_options = Subject.all
      end
    
    def set_question
      @question = Question.find(params[:id])
    end
  
    def params_question
        params_question = params.require(:question).permit(:description, :subject_id, 
          answers_attributes: [:id, :description, :correct, :_destroy])
    end
  
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
    before_action :set_subject, only: [:edit,:update, :destroy]
  
    def index
      @subjects = Subject.all.order(:description).page(params[:page])
    end
  
    def new 
      @subject = Subject.new
    end
  
    def create
      @subject = Subject.new(params_subject)
      if @subject.save
        redirect_to admins_backoffice_subjects_path, notice: "Subject included sucessfuly"
      elsif
        #renderizar de novo
        render :new
      end
    end
  
    def edit
    end
    
    def update
      if @subject.update(params_subject)
        redirect_to admins_backoffice_subjects_path, notice: "Subject saved sucessfuly"
      elsif
        #renderizar de novo
        render :edit
      end
    end
  
    def destroy
      if @subject.destroy
        redirect_to admins_backoffice_subjects_path, notice: "Subject deleted sucessfuly"
      elsif
        #renderizar de novo
        render :index
      end
    end
  
    private
    
    def set_subject
      @subject = Subject.find(params[:id])
    end
  
    def params_subject
      params_subject = params.require(:subject).permit(:description)
    end
  
  end
  

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "admins_backoffice"
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attributes(object = nil, method = nil)
        if object && method
            object.model.human_attribute_name(method) 
        end
    end
end

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form', locals: { action_message: "Edit"}%>

app/views/admins_backoffice/subjects/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Subjects</h1>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th><%= translate_attributes(@subjects, :description) %></th>
        <th>
          <%= link_to new_admins_backoffice_subject_path, class:"btn btn-success btn-circle" do %>
            <i class="fa fa-plus"></i>
          <% end %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @subjects.each do |subject| %>
        <tr>
          <td><%= subject.id %></td>
          <td><%= subject.description %></td>
          <td style="width:150px">
            <%= link_to edit_admins_backoffice_subject_path(subject), class:"btn btn-primary btn-circle" do %>
              <i class="fa fa-edit"></i>
            <% end %>
            <%= link_to admins_backoffice_subjects_path(subject), method: :delete, 
              class:"btn btn-danger btn-circle", data: {confirm: "Are you sure?"} do %>
              <i class="fa fa-minus"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @subjects%>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form', locals: { action_message: "New"}%>